# Generated by Django 5.1.2 on 2024-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='hello', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='world',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
