# Generated by Django 5.1.2 on 2024-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='world',
            field=models.TextField(blank=True, null=True),
        ),
    ]
